// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwlcrwgpvxyxfziywbcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3bGNyd2dwdnh5eGZ6aXl3YmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzIwNDgsImV4cCI6MjA2MTEwODA0OH0.3RrhQz1chDUCgfmCPTX0U2QkQVQm3mlfw3eiVe3R5SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);